language: node_js
node_js:
  - "node"
before_install:
  - npm i -g makeshift && makeshift -s @bcoe -r https://registry.npmjs.org
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: cristian_brokate@hotmail.com
  on:
    tags: true
